# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Scurid
theme:
  # currently used theme for the docs
  name: material
  palette:
    primary: black
  features:
    # used for defining the navigation configuration
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - content.tabs.link
plugins:
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
      # uses the version specified via `mike deploy`
  # enables the tags on every page
  - tags
  # enables the search bar, with search functionality
  - search
markdown_extensions:
  # enables the tabs options on the pages
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # Used for aligning the images
  - attr_list
  - md_in_html
# used for controlling the pages and the sub tree under the pages on the doc
nav:
  - Home: 'index.md'
  - 'Getting started':
      - 'Quickstart': 'quickstart.md'
      - 'Zero-trust to trusted Device Identity': 'zero-trusttotrustedIdentityforyourIoTDevice.md'
      - 'Autonomous Device and agent setup': 'autonomousDeviceOnboarding.md'
      - 'Identity Context enabled file transfer': 'identityContextEnabledFileTransfer.md'
      - 'Logging': 'logs.md'
      - 'Glossary': 'glossary.md'
  - 'MicroScurid':
      - 'How to Get Started with Microscurid': 'gettingStartedMicroscurid.md'
      - 'Create Identity Using Microscurid': 'createIdentity.md'
      - 'How to Setup TLS Using Microscurid': 'setupTLS.md'
      - 'Handling the Registration Request of Identity on the Scurid App': 'registrationRequestOfIdentity.md'
  - 'Integrate':
      - 'Scurid Distributed ID for PTC ThingWorx IoT platform': 'integration-thingworx.md'
  - 'Blogs':
      - 'An end-to-end example of how to integrate MicroScurid-C with your STMicrocontroller board.': 'blog-microscurid.md'
  - 'APIs':
      - 'gRPC':
          - 'Scurid Edge Agent': 'edgeAgent.md'
          - 'Scurid Backend':
              - 'Auth' : 'auth.md'
              - 'Platform API' : 'platformapi.md'
              - 'Platform API v2' : 'platformapiv2.md'
              - 'Device Context' : 'deviceContext.md'
              - 'Device Data' : 'deviceData.md'
              - 'MicroScurid' : 'microscurid.md'
              - 'Logs' : 'logapi.md'
  - 'Releases':
      - 'Scurid Release Notes': 'releasenotes.md'
extra:
  analytics:
    provider: google
    property: G-ZCT4VBJY2H
  homepage: https://scurid.com
  # enables icons in the Footer
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/scurid_me
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/scurid-ai-tech
    - icon: fontawesome/brands/slack
      link: https://scurid-community.slack.com/
    - icon: fontawesome/brands/medium
      link: https://scurid.medium.com/
  version:
    provider: mike
    default: latest
  # disables the footer with mkdocs info
  generator: true
copyright: Copyright &copy; 2022 Scurid Inc. and others