# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Scurid
theme:
  logo: img/scurid/logo/scurid-logo.png
  favicon: img/scurid/logo/favicon.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  # currently used theme for the docs
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # used for defining the navigation configuration
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
plugins:
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false, to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
      # uses the version specified via `mike deploy`
  # enables the tags on every page
  - tags
  # enables the search bar, with search functionality
  - search
markdown_extensions:
  # enables the tabs options on the pag
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # Used for aligning the images
  - attr_list
  - md_in_html
# used for controlling the pages and the subtree under the pages on the doc
nav:
  - Home: 'index.md'
  - 'Get started':
      - 'Overview': 'quickstart-overview.md'
      - 'Deployment Options': 'deployment-options.md'
      - 'Quickstart':
        - 'On Premise': 'quickstart/quickstart-on-premise.md'
        - 'Managed': 'quickstart/quickstart-for-managed.md'
      - 'App':
        - 'Startup Configuration': update_app_startup_config.md
        - 'Logging':
           - 'Overview': 'logs.md'
           - 'Features': 'log_features.md'
      - 'Glossary': 'glossary.md'
  - User Management: 'users.md'
  - Monitoring: 'monitoring.md'
  - 'For Edge':
      - 'Scurid Edge Agent':
        - 'Zero-trust to trusted Device Identity': 'zero-trusttotrustedIdentityforyourIoTDevice.md'
        - 'Autonomous Device and agent setup': 'autonomousDeviceOnboarding.md'
        - 'Identity Context enabled file transfer': 'identityContextEnabledFileTransfer.md'
      - 'MicroScurid-C SDK':
        - 'How to Get Started with MicroScurid-C SDK': 'gettingStartedMicroscurid.md'
        - 'Create Identity Using MicroScurid-C SDK': 'createIdentity.md'
        - 'How to Setup TLS Using MicroScurid-C SDK': 'setupTLS.md'
        - 'Handling the Registration Request of Identity on the Scurid App': 'registrationRequestOfIdentity.md'
  - 'Integrate':
      - 'Scurid Distributed ID for PTC ThingWorx IoT platform': 'integration-thingworx.md'
  - 'Blogs':
      - 'An end-to-end example of how to integrate MicroScurid-C with your STMicrocontroller board.': 'blog-microscurid.md'
  - 'APIs':
      - 'gRPC':
          - 'For Edge':
            - 'Scurid Edge Agent': 'edgeAgent.md'
            - 'MicroScurid-C SDK' : 'microscurid.md'
          - 'Server':
              - 'Auth' : 'auth.md'
              - 'Platform API' : 'platformapi.md'
              - 'Platform API v2' : 'platformapiv2.md'
              - 'Device Context' : 'deviceContext.md'
              - 'Device Data' : 'deviceData.md'
              - 'Logs' : 'logapi.md'
              - 'Certificate' : 'certificate.md'
              - 'Integration' : 'integration.md'
              - 'Platform Internal' : 'platform-internals.md'
              - 'Signature' : 'signature.md'
  - 'Releases':
      - 'Scurid Release Notes': 'releasenotes.md'
extra:
  analytics:
    provider: google
    property: G-ZCT4VBJY2H
  homepage: https://scurid.com
  # enables icons in the Footer
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ScuridInc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/scurid-inc/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/scurid-community/shared_invite/zt-23un0enx0-W8vVMyYR_QtCWJQ04xBsTw
  version:
    provider: mike
    default: latest
  # disables the footer with mkdocs info
  generator: true
copyright: Copyright &copy; 2022 Scurid Inc. and others